application: pic-peck
version: 1
runtime: python27
api_version: 1
threadsafe: yes
handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /scripts
  static_dir: scripts
- url: /i
  static_dir: i
- url: /.*
  script: imageManipulation.app


libraries:
- name: PIL
  version: "1.1.7"
- name: jinja2
  version: latest